Repository AliMD/blog, pull requests merged in 2023-09, with the labels that each got.

#1 feat: customize for AliMD
  .github/CODEOWNERS
  .github/workflows/build.yaml
  .github/workflows/publish-alwatr-container.yml
  .vscode/settings.json
  README.md
  assets/img/authors/alimd.jpg
  assets/img/authors/njfamirm.jpg
  cloud/env/12fy-ws-beta.env
  cloud/env/12fy-ws.env
  cloud/env/alimd-blog-beta.env
  cloud/env/alimd-blog-ws.env
  package.json
  shortcode/edit-on-github.js
  site/_data/site.json
  site/en/about.njk
  site/en/blog/blog.json
  site/en/blog/sample-post.md
  site/en/home.njk
  yarn.lock
Labels: enhancement

#4 docs(blog-post): add data-type in es
  .vscode/settings.json
  assets/img/blog/intro-to-ecmascript-data-type/cover.jpg
  eleventy.config.cjs
  shortcode/link.js
  site/_css/blog-post.css
  site/_includes/blog-post-list.njk
  site/_layouts/blog-post.njk
  site/en/blog/ecmascript-data-type.md
  site/en/blog/intro-to-javascript.md
  site/en/blog/sample-post.md
  site/en/home.njk
Labels: documentation

#7 feat: new theme
  assets/font/inter/inter-100.woff
  assets/font/inter/inter-200.woff
  assets/font/inter/inter-300.woff
  assets/font/inter/inter-400.woff
  assets/font/inter/inter-500.woff
  assets/font/inter/inter-600.woff
  assets/font/inter/inter-700.woff
  assets/font/inter/inter-800.woff
  assets/font/inter/inter-900.woff
  assets/font/inter/inter[wght].woff2
  assets/font/lexend/lexend-100.woff
  assets/font/lexend/lexend-200.woff
  assets/font/lexend/lexend-300.woff
  assets/font/lexend/lexend-400.woff
  assets/font/lexend/lexend-500.woff
  assets/font/lexend/lexend-600.woff
  assets/font/lexend/lexend-700.woff
  assets/font/lexend/lexend-800.woff
  assets/font/lexend/lexend-900.woff
  assets/font/lexend/lexend[wght].woff2
  config/markdown.js
  eleventy.config.cjs
  package.json
  shortcode/link.js
  site/_css/blog-post.css
  site/_css/inter-font.css
  site/_css/lexend-font.css
  site/_css/main.css
  site/_css/syntax-highlighter.css
  site/_includes/blog-post-list.njk
  site/_includes/header.njk
  site/_js/header.ts
  site/_js/script.ts
  site/_js/table-of-content.ts
  site/_layouts/base.njk
  site/_layouts/blog-post.njk
  site/en/blog/intro-to-ecmascript-data-type.md
  yarn.lock
Labels: new-feature
